/*
 * IMU_Conductor.h
 *
 *  Created on: May 16, 2026
 *      Author: Evan McGinnis
 */

#ifndef IMU_CONDUCTOR_H_
#define IMU_CONDUCTOR_H_

#include <main.h>
#include <IMU_Config.h>
#include <IMU_Hardware.h>
#include <IMU_Model.h>


/*
* Requires: hi2c is I2C_HandleTypeDef object generated by cubeMX
* Modifies: 
* Effects:
*/
void IMU_init(I2C_HandleTypeDef* hi2c);

void IMU_update_model(IMU_Model_t* imu_model);
#endif /* IMU_CONDUCTOR_H_ */
