/*
 * IMU_Config.h
 *
 *  Created on: May 16, 2026
 *      Author: Evan McGinnis
 * Allows the user to set pre-compile default sensor configuration settings. NOTE: If user chooses a fusion sensor mode,
 * all individual sensor configuration settings will be ignored. 
 */

#ifndef SRC_IMU_CONFIG_H_
#define SRC_IMU_CONFIG_H_

#include "IMU_Hardware.h"

/*****************************
 * IMU SENSOR DEFAULT CONFIG *
 *****************************/
/*
    IMU_OPR_MODE_ACCONLY = 0x01,
    IMU_OPR_MODE_MAGONLY = 0x02,
    IMU_OPR_MODE_GYROONLY = 0x03,
    IMU_OPR_MODE_ACCMAG = 0x04,
    IMU_OPR_MODE_ACCGYRO = 0x05,
    IMU_OPR_MODE_MAGGYRO = 0x06,
    IMU_OPR_MODE_AMG = 0x07,
    IMU_OPR_MODE_IMU = 0x08,
    IMU_OPR_MODE_COMPASS = 0x09,
    IMU_OPR_MODE_M4G = 0x0A,
    IMU_OPR_MODE_NDOF_FMC_OFF = 0x0B,
    IMU_OPR_MODE_NDOF = 0x0C
*/
#define IMU_OPR_MODE IMU_OPR_MODE_IMU

/*
* IMU_ACCEL_RANGE_2G = 0x00u,
* IMU_ACCEL_RANGE_4G = 0x01u,
* IMU_ACCEL_RANGE_8G = 0x02u,
* IMU_ACCEL_RANGE_16G = 0x03u
*/
#define IMU_ACCEL_RANGE IMU_ACCEL_RANGE_2G
/*
* IMU_ACCEL_BANDWIDTH_8HZ  (7.81Hz)
* IMU_ACCEL_BANDWIDTH_16HZ (15.63Hz)
* IMU_ACCEL_BANDWIDTH_31HZ (31.25Hz)
* IMU_ACCEL_BANDWIDTH_63HZ (62.5Hz)
* IMU_ACCEL_BANDWIDTH_125HZ
* IMU_ACCEL_BANDWIDTH_250HZ
* IMU_ACCEL_BANDWIDTH_500HZ
* IMU_ACCEL_BANDWIDTH_1000HZ
*/
#define IMU_ACCEL_BANDWIDTH IMU_ACCEL_BANDWIDTH_63HZ
/*
* IMU_ACCEL_OPR_MODE_NORMAL
* IMU_ACCEL_OPR_MODE_SUSPEND
* IMU_ACCEL_OPR_MODE_LOW_1
* IMU_ACCEL_OPR_MODE_STANDBY
* IMU_ACCEL_OPR_MODE_LOW_2
* IMU_ACCEL_OPR_MODE_DEEP_SUSPEND
*/
#define IMU_ACCEL_OPR_MODE IMU_ACCEL_OPR_MODE_NORMAL
/*
* IMU_GYRO_RANGE_2000DPS
* IMU_GYRO_RANGE_1000DPS
* IMU_GYRO_RANGE_500DPS
* IMU_GYRO_RANGE_250DPS
* IMU_GYRO_RANGE_125DPS
*/
#define IMU_GYRO_RANGE IMU_GYRO_RANGE_1000DPS
/*
* IMU_GYRO_BANDWIDTH_523HZ
* IMU_GYRO_BANDWIDTH_230HZ
* IMU_GYRO_BANDWIDTH_116HZ
* IMU_GYRO_BANDWIDTH_47HZ
* IMU_GYRO_BANDWIDTH_23HZ
* IMU_GYRO_BANDWIDTH_12HZ
* IMU_GYRO_BANDWIDTH_64HZ
* IMU_GYRO_BANDWIDTH_32HZ
*/
#define IMU_GYRO_BANDWIDTH IMU_GYRO_BANDWIDTH_47HZ
/*
IMU_GYRO_OPR_MODE_NORMAL =       0x00u,
IMU_GYRO_OPR_MODE_FAST_PWR_UP =  0x01u,
IMU_GYRO_OPR_MODE_DEEP_SUSPEND = 0x02u,
IMU_GYRO_OPR_MODE_SUSPEND =      0x03u,
IMU_GYRO_OPR_MODE_ADV_POW_SAVE = 0x04u,
*/
#define IMU_GYRO_OPR_MODE IMU_GYRO_OPR_MODE_NORMAL
/*
IMU_MAG_RATE_2HZ =  0x00u,
IMU_MAG_RATE_6HZ =  0x01u,
IMU_MAG_RATE_8HZ =  0x02u,
IMU_MAG_RATE_10HZ = 0x03u,
IMU_MAG_RATE_15HZ = 0x04u,
IMU_MAG_RATE_20HZ = 0x05u,
IMU_MAG_RATE_25HZ = 0x06u,
IMU_MAG_RATE_30HZ = 0x07u
*/
#define IMU_MAG_RATE IMU_MAG_RATE_10HZ
/* 
IMU_MAG_OPR_MODE_LOW_PWR =          0x00u,
IMU_MAG_OPR_MODE_REGULAR =          0x01u,
IMU_MAG_OPR_MODE_ENHANCED_REGULAR = 0x02u,
IMU_MAG_OPR_MODE_HIGH_ACCURACY =    0x03u  
*/
#define IMU_MAG_OPR_MODE IMU_MAG_OPR_MODE_REGULAR
/* 
* IMU_MAG_PWR_MODE_NORMAL,
* IMU_MAG_PWR_MODE_SLEEP,
* IMU_MAG_PWR_MODE_SUSPEND,
* IMU_MAG_PWR_MODE_FORCE_MODE,
*/
#define IMU_MAG_PWR_MODE IMU_MAG_PWR_MODE_NORMAL

/****************************
 * 		UNIT SELECTION      *
 ****************************/

/*
 * accel unit options:
 * m/s^2: IMU_UNIT_SEL_ACCEL_MS2
 * mg:    IMU_UNIT_SEL_ACCEL_MG
 */
#define IMU_ACCEL_UNITS IMU_UNIT_SEL_ACCEL_MS2
/*
 * Angular rate unit options:
 * Dps: IMU_UNIT_SEL_ANGULAR_RATE_DPS
 * Rps: IMU_UNIT_SEL_ANGULAR_RATE_RPS
 */
#define IMU_ANGULAR_RATE_UNITS IMU_UNIT_SEL_ANGULAR_RATE_DPS
/*
 * Euler angle unit options:
 * Degrees: IMU_UNIT_SEL_EULER_ANGLE_DEG
 * Radians: IMU_UNIT_SEL_EULER_ANGLE_RAD
 */
#define IMU_EULER_ANGLE_UNITS IMU_UNIT_SEL_EULER_ANGLE_DEG
/*
 * Temperature unit options:
 * Celsius: IMU_UNIT_SEL_TEMP_C
 * Farenheit: IMU_UNIT_SEL_TEMP_F
 */
#define IMU_TEMP_UNITS IMU_UNIT_SEL_TEMP_C

//DO NOT MODIFY CODE BELOW
// scalars are from BNO055 datasheet
#if IMU_ACCEL_UNITS == IMU_UNIT_SEL_ACCEL_MS2
	#define IMU_ACCEL_SCALAR 100
#elif IMU_ACCEL_UNITS == IMU_UNIT_SEL_ACCEL_MG
	#define IMU_ACCEL_SCALAR 1
#else
	#error "invalid acceleration unit selection"
#endif

#if IMU_ANGULAR_RATE_UNITS == IMU_UNIT_SEL_ANGULAR_RATE_DPS
	#define IMU_ANGULAR_RATE_SCALAR 16
#elif IMU_ANGULAR_RATE_UNITS == IMU_UNIT_SEL_ANGULAR_RATE_RPS
	#define IMU_ANGULAR_RATE_SCALAR 900
#else
	#error "invalid angular rate unit selection"
#endif

#if IMU_EULER_ANGLE_UNITS == IMU_UNIT_SEL_EULER_ANGLE_DEG
	#define IMU_EULER_ANGLE_SCALAR 16
#elif IMU_EULER_ANGLE_UNITS == IMU_UNIT_SEL_EULER_ANGLE_RAD
	#define IMU_EULER_ANGLE_SCALAR 900
#else
	#error "invalid euler angle unit selection"
#endif

#if IMU_TEMP_UNITS == IMU_UNIT_SEL_TEMP_C
	#define IMU_TEMP_SCALAR 1
#elif IMU_TEMP_UNITS == IMU_UNIT_SEL_TEMP_F
	#define IMU_TEMP_SCALAR 1
#else
	#error "invalid temperature unit selection"
#endif


#define IMU_MAG_SCALAR 16
#define IMU_QUAT_SCALAR (1 << 14)
#endif /* SRC_IMU_CONFIG_H_ */
